#!/usr/bin/env python3
#-----------------------------------------------------------------#
import asyncio
from tcp import Servidor
import scripts.Message_Handler as MH
#-----------------------------------------------------------------#
servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(MH.conexao_aceita)
asyncio.get_event_loop().run_forever()
#-----------------------------------------------------------------#